#!/bin/bash

set -eo pipefail
trap exit INT TERM

####

printf "[info] cleaning\n"

rm -rf /go/src/github.com/jancajthaml/target/* &> /dev/null || :

printf "[info] building\n"

cd /go/src/datadog-mock

go clean

CGO_ENABLED=0 GOOS=${GOOS} go build -a -installsuffix cgo -o /go/src/github.com/jancajthaml/target/datadog_mock

printf "[info] done, built sparrow/datadog_mock\n"
